### ISSUE TITLE
D:\KDP-compatible-driver-loader-main\Loader>Loader.exe gdrv.sys CloudDisk.sys Failed to load driver service \Registry\Machine\System\CurrentControlSet\Services\gdrv. NtLoadDriver: C0000603.

### ISSUE THREAD

**Issue by huddhudd** [0mWindyBug/KDP-compatible-driver-loader#1]
D:\KDP-compatible-driver-loader-main\Loader>Loader.exe gdrv.sys CloudDisk.sys
Failed to load driver service \Registry\Machine\System\CurrentControlSet\Services\gdrv. NtLoadDriver: C0000603.

**Comment by 0mWindyBug** [comment]
Can you manually (with sc for instance ) load gdrv.sys?

**Comment by 0mWindyBug** [comment]
Anyways , if you can’t load gdrv.sys manually it’s probably because it’s been blacklisted . Just use another vulnerable driver there are plenty out there
