### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by cosmopolitic** [0mWindyBug/KDP-compatible-driver-loader#13]
![error](https://github.com/user-attachments/assets/4196e573-b18c-4c8d-b4db-7592c463bc4a)

**Comment by 0mWindyBug** [comment]
Is your system in safe mode? just by googling the error code ….

**Comment by cosmopolitic** [comment]
yes my system in safe mode other ways ı get blue screen error

**Comment by 0mWindyBug** [comment]
Blue screen by? Anyways, that’s the reason you can’t load the gdrv driver I guess …
