### ISSUE TITLE
Loader calculates the seCiCallbacsInstr wrong in case of a carry over

### ISSUE THREAD

**Issue by rafaelscheel** [0mWindyBug/KDP-compatible-driver-loader#3]
The LEA instruction searched for in getCiValidateImageHeaderEntry in Loader.cpp performs 32bit math. The current code does 64bit math.
The issue was hiddne, since %x was used instead of %p for the output of 64bit addresses. 

This leads to a wronggly calculated seCiCallbacksAddr and to a blue screen. So far this seems to only affect windows server operating systems. 

I provide a fix in a forked repo and create the pull request today. 

P.S. my first time contributing to open source code, so let me know if this is not the right approach ;)

**Comment by 0mWindyBug** [comment]
Thanks for pointing it out
