### ISSUE TITLE
now patchguarded

### ISSUE THREAD

**Issue by fork1488** [0mWindyBug/KDP-compatible-driver-loader#9]
dead

**Comment by fork1488** [comment]
![image](https://github.com/0mWindyBug/KDP-compatible-driver-loader/assets/87487867/5eef5b88-b607-49b0-b2ac-e683decbce72)

**Comment by 0mWindyBug** [comment]
SeCiCallbacks? Well , it’s not entirely dead since we swap the pointer temporarily having a read primitive

**Comment by fork1488** [comment]
> SeCiCallbacks? Well , it’s not entirely dead since we swap the pointer temporarily having a read primitive

temporarily doesn't count
